name: Tests

on:
  push:
    branches: "*"
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: master
    paths-ignore:
    - 'docs/**'

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: 🔁 Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: 🔁 Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: pangeo-forge-recipes
          use-mamba: true
      - name: 🎯 Set cache number
        id: cache-number
        # cache will last 3 days by default
        run: echo CACHE_NUMBER=`expr $(date +'%j') / 3` >> $GITHUB_ENV
      - name: 🎯 Set environment file
        id: env-file
        run: echo "env_file=ci/py${{ matrix.python-version }}.yml" >> $GITHUB_ENV
      - uses: actions/cache@v2
        name: 🗃 Cache environment
        with:
          path: /usr/share/miniconda3/envs/pangeo-forge-recipes
          key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles( env.env_file ) }}-${{ env.CACHE_NUMBER }}
        id: conda-cache
      - name: 🐫 Maybe Update environment
        if: steps.conda-cache.outputs.cache-hit != 'true'
        run: mamba env update -n pangeo-forge-recipes -f ${{ env.env_file }}
      - name: 🐍 List conda env
        shell: bash -l {0}
        run: |
          conda info
          conda list
  run-tests:
    needs: prepare-env
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        pytest-mark: ["no_executor", "executor_python", "executor_dask", "executor_prefect", "executor_prefect_dask"]
    steps:
      - uses: actions/checkout@v2
      - name: 🎯 Set cache number
        id: cache-number
        # cache will last 3 days by default
        run: echo CACHE_NUMBER=`expr $(date +'%j') / 3` >> $GITHUB_ENV
      - name: 🎯 Set environment file
        id: env-file
        run: echo "env_file=ci/py${{ matrix.python-version }}.yml" >> $GITHUB_ENV
      - uses: actions/cache@v2
        name: 🗃 Loaded Cached environment
        with:
          path: /usr/share/miniconda3/envs/pangeo-forge-recipes
          key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles( env.env_file ) }}-${{ env.CACHE_NUMBER }}
        id: conda-cache
      - name: 🤿  Bail out if no cache hit
        if: steps.conda-cache.outputs.cache-hit != 'true'
        run: false
      - name: 🎯 Set path to include conda python
        run: echo "/usr/share/miniconda3/envs/pangeo-forge-recipes/bin" >> $GITHUB_PATH
      - name: 🌈 Install pangeo-forge-recipes package
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e  .
      - name: 🏄‍♂️ Run Tests
        shell: bash -l {0}
        run: |
          py.test tests -v -m ${{ matrix.pytest-mark }} \
            --cov=pangeo_forge_recipes --cov-config .coveragerc \
            --cov-report term-missing \
            --cov-report xml \
            --durations=10 --durations-min=1.0
      - name: 🚦 Run Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
