name: Tests

on:
  push:
    branches: "*"
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: master
    paths-ignore:
    - 'docs/**'

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          # activate-environment: pangeo-forge-recipes
          use-mamba: true
      - name: Set cache number
        run: echo "::set-output name=number::$(date +'%d%m')"
        id: cache-number
      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/pangeo-forge-recipes
          key: ${{ runner.os }}-conda-${{ hashFiles('ci/*.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: ${{ steps.cache-number.outputs.number }}
        id: conda-cache
      - name: Update environment
        run: mamba env update -n pangeo-forge-recipes -f ci/py${{ matrix.python-version }}.yml
        if: steps.conda-cache.outputs.cache-hit != 'true'
      - name: Activate conda env
        shell: bash -l {0}
        run: |
          conda activate pangeo-forge-recipes
          conda info
          conda list
      - name: install pangeo-forge-recipes
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e  .
      - name: Run Tests
        shell: bash -l {0}
        run: |
          py.test tests -v --redirect-dask-worker-logs-to-stdout=DEBUG \
            --cov=pangeo_forge_recipes --cov-config .coveragerc \
            --cov-report term-missing \
            --cov-report xml \
            --durations=10 --durations-min=1.0
      - name: Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
